dist: trusty
language: java
jdk:
  - openjdk8
install: true
script: '[ "$TRAVIS_REPO_SLUG" == veithen/filecheck ] && [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == false ] && goal=deploy || goal=install ; mvn -B -s .travis-settings.xml $goal'
env:
  global:
    - secure: "oI6Xqy0dUNVX3aVQqiWZPQh90s+4k5EQrnf9LBYqAY9XK/+Gsl/zO1DY/12jbStvli3icOdpCXnI+FqKmqISZA7pqNov9P6byyFJ7Gw9CbWAUvTm4PowlmexVLMGLjnSKLjIR78nGXJECExzeL3/aiuw+5mfH9cTzoeIM0UQ01c="
cache:
  directories:
  - $HOME/.m2
